name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login -u "sandy06" --password-stdin
        docker image build -t sandy06/fetch_models:initial .
        docker push sandy06/fetch_models:initial
